### ISSUE TITLE
Running to_liquid of an Existing Money Object Returns Cents

### ISSUE THREAD

**Issue by stephenreid** [Shopify/money#12]
Experiencing this issue with invoices

``` ruby
[4] pry(main)> money = Money.new(Money.new(10.01)).to_liquid
=> 1001
```

Looks like an issue at https://github.com/Shopify/money/blob/master/lib/money/money.rb#L126

Not sure why that should return cents instead of a formatted string.

**Comment by elfassy** [comment]
Hi @stephenreid 
I agree with you this implementation is strange. This will need to go through a deprecation cycle before it can be modified, since this has been the expected behavior for 7+ years. For now please use `to_s` instead of `to_liquid`. I think we should remove `to_liquid` all together since it's presentation logic that should not be in the money gem.

**Comment by tjoyal** [comment]
With the [removal of Liquid specific logic](https://github.com/Shopify/money/pull/221/files#diff-bd2a478c15a8b72ca472f9636e2b08e1bb84afdac3c029869c2a38110956c289L246) from the gem, I think this issue is safe to be closed.
