### ISSUE TITLE
Parsing is incorrect if there are more than two numbers after the decimal point

### ISSUE THREAD

**Issue by davidcornu** [Shopify/money#13]
**Shopify/money**

```
irb(main):001:0> require 'money'
=> true
irb(main):002:0> "1.11111111".to_money
=> #<Money value:111111111.00>
irb(main):003:0> "1.11111111".to_money.to_f
=> 111111111.0
```

**RubyMoney/monetize** (https://github.com/RubyMoney/monetize)

```
irb(main):001:0> require 'monetize'
=> true
irb(main):002:0> "1.11111111".to_money
=> #<Money fractional:111 currency:USD>
irb(main):003:0> "1.11111111".to_money.to_f
=> 1.11
```

Discovered by @byroot

**Comment by NBowes** [comment]
I have a partner who is experiencing this same issue with the `UsageCharge` API. 
[Internal Dashboard](https://app.shopify.com/services/internal/shops/18485575)

```
usage_charge = {
'price': 1.035,
'description': 'ION usage charge'
}
usage_charge = ShopifyAPI::UsageCharge.new(usage_charge)
```

They are seeing the price being charged is `1035` instead of a rounded `1.04`. They also sent in an example of what this looks like for their charges:

![](https://screenshot.click/04-12-nh4kf-t9hyb.png)

Just wondering if we've made any progress on this yet?

Thanks!
[Zendesk Ticket](https://shopify.zendesk.com/agent/tickets/6250376)
